/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spinfosec.parse.bean;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-11-27")
public class ParseParams implements org.apache.thrift.TBase<ParseParams, ParseParams._Fields>, java.io.Serializable, Cloneable, Comparable<ParseParams> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ParseParams");

  private static final org.apache.thrift.protocol.TField STREAM_FIELD_DESC = new org.apache.thrift.protocol.TField("stream", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField FILE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("fileName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ENABLE_OCR_FIELD_DESC = new org.apache.thrift.protocol.TField("enableOCR", org.apache.thrift.protocol.TType.BOOL, (short)3);
  private static final org.apache.thrift.protocol.TField ENABLE_OFFICE_OCR_FIELD_DESC = new org.apache.thrift.protocol.TField("enableOfficeOCR", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField ENABLE_PDF_OCR_FIELD_DESC = new org.apache.thrift.protocol.TField("enablePdfOCR", org.apache.thrift.protocol.TType.BOOL, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ParseParamsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ParseParamsTupleSchemeFactory());
  }

  public ByteBuffer stream; // required
  public String fileName; // required
  public boolean enableOCR; // required
  public boolean enableOfficeOCR; // required
  public boolean enablePdfOCR; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STREAM((short)1, "stream"),
    FILE_NAME((short)2, "fileName"),
    ENABLE_OCR((short)3, "enableOCR"),
    ENABLE_OFFICE_OCR((short)4, "enableOfficeOCR"),
    ENABLE_PDF_OCR((short)5, "enablePdfOCR");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STREAM
          return STREAM;
        case 2: // FILE_NAME
          return FILE_NAME;
        case 3: // ENABLE_OCR
          return ENABLE_OCR;
        case 4: // ENABLE_OFFICE_OCR
          return ENABLE_OFFICE_OCR;
        case 5: // ENABLE_PDF_OCR
          return ENABLE_PDF_OCR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ENABLEOCR_ISSET_ID = 0;
  private static final int __ENABLEOFFICEOCR_ISSET_ID = 1;
  private static final int __ENABLEPDFOCR_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STREAM, new org.apache.thrift.meta_data.FieldMetaData("stream", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.FILE_NAME, new org.apache.thrift.meta_data.FieldMetaData("fileName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ENABLE_OCR, new org.apache.thrift.meta_data.FieldMetaData("enableOCR", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ENABLE_OFFICE_OCR, new org.apache.thrift.meta_data.FieldMetaData("enableOfficeOCR", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ENABLE_PDF_OCR, new org.apache.thrift.meta_data.FieldMetaData("enablePdfOCR", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ParseParams.class, metaDataMap);
  }

  public ParseParams() {
    this.enableOCR = true;

    this.enableOfficeOCR = true;

    this.enablePdfOCR = true;

  }

  public ParseParams(
    ByteBuffer stream,
    String fileName,
    boolean enableOCR,
    boolean enableOfficeOCR,
    boolean enablePdfOCR)
  {
    this();
    this.stream = org.apache.thrift.TBaseHelper.copyBinary(stream);
    this.fileName = fileName;
    this.enableOCR = enableOCR;
    setEnableOCRIsSet(true);
    this.enableOfficeOCR = enableOfficeOCR;
    setEnableOfficeOCRIsSet(true);
    this.enablePdfOCR = enablePdfOCR;
    setEnablePdfOCRIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ParseParams(ParseParams other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetStream()) {
      this.stream = org.apache.thrift.TBaseHelper.copyBinary(other.stream);
    }
    if (other.isSetFileName()) {
      this.fileName = other.fileName;
    }
    this.enableOCR = other.enableOCR;
    this.enableOfficeOCR = other.enableOfficeOCR;
    this.enablePdfOCR = other.enablePdfOCR;
  }

  public ParseParams deepCopy() {
    return new ParseParams(this);
  }

  @Override
  public void clear() {
    this.stream = null;
    this.fileName = null;
    this.enableOCR = true;

    this.enableOfficeOCR = true;

    this.enablePdfOCR = true;

  }

  public byte[] getStream() {
    setStream(org.apache.thrift.TBaseHelper.rightSize(stream));
    return stream == null ? null : stream.array();
  }

  public ByteBuffer bufferForStream() {
    return org.apache.thrift.TBaseHelper.copyBinary(stream);
  }

  public ParseParams setStream(byte[] stream) {
    this.stream = stream == null ? (ByteBuffer)null : ByteBuffer.wrap(Arrays.copyOf(stream, stream.length));
    return this;
  }

  public ParseParams setStream(ByteBuffer stream) {
    this.stream = org.apache.thrift.TBaseHelper.copyBinary(stream);
    return this;
  }

  public void unsetStream() {
    this.stream = null;
  }

  /** Returns true if field stream is set (has been assigned a value) and false otherwise */
  public boolean isSetStream() {
    return this.stream != null;
  }

  public void setStreamIsSet(boolean value) {
    if (!value) {
      this.stream = null;
    }
  }

  public String getFileName() {
    return this.fileName;
  }

  public ParseParams setFileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

  public void unsetFileName() {
    this.fileName = null;
  }

  /** Returns true if field fileName is set (has been assigned a value) and false otherwise */
  public boolean isSetFileName() {
    return this.fileName != null;
  }

  public void setFileNameIsSet(boolean value) {
    if (!value) {
      this.fileName = null;
    }
  }

  public boolean isEnableOCR() {
    return this.enableOCR;
  }

  public ParseParams setEnableOCR(boolean enableOCR) {
    this.enableOCR = enableOCR;
    setEnableOCRIsSet(true);
    return this;
  }

  public void unsetEnableOCR() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ENABLEOCR_ISSET_ID);
  }

  /** Returns true if field enableOCR is set (has been assigned a value) and false otherwise */
  public boolean isSetEnableOCR() {
    return EncodingUtils.testBit(__isset_bitfield, __ENABLEOCR_ISSET_ID);
  }

  public void setEnableOCRIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ENABLEOCR_ISSET_ID, value);
  }

  public boolean isEnableOfficeOCR() {
    return this.enableOfficeOCR;
  }

  public ParseParams setEnableOfficeOCR(boolean enableOfficeOCR) {
    this.enableOfficeOCR = enableOfficeOCR;
    setEnableOfficeOCRIsSet(true);
    return this;
  }

  public void unsetEnableOfficeOCR() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ENABLEOFFICEOCR_ISSET_ID);
  }

  /** Returns true if field enableOfficeOCR is set (has been assigned a value) and false otherwise */
  public boolean isSetEnableOfficeOCR() {
    return EncodingUtils.testBit(__isset_bitfield, __ENABLEOFFICEOCR_ISSET_ID);
  }

  public void setEnableOfficeOCRIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ENABLEOFFICEOCR_ISSET_ID, value);
  }

  public boolean isEnablePdfOCR() {
    return this.enablePdfOCR;
  }

  public ParseParams setEnablePdfOCR(boolean enablePdfOCR) {
    this.enablePdfOCR = enablePdfOCR;
    setEnablePdfOCRIsSet(true);
    return this;
  }

  public void unsetEnablePdfOCR() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ENABLEPDFOCR_ISSET_ID);
  }

  /** Returns true if field enablePdfOCR is set (has been assigned a value) and false otherwise */
  public boolean isSetEnablePdfOCR() {
    return EncodingUtils.testBit(__isset_bitfield, __ENABLEPDFOCR_ISSET_ID);
  }

  public void setEnablePdfOCRIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ENABLEPDFOCR_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STREAM:
      if (value == null) {
        unsetStream();
      } else {
        setStream((ByteBuffer)value);
      }
      break;

    case FILE_NAME:
      if (value == null) {
        unsetFileName();
      } else {
        setFileName((String)value);
      }
      break;

    case ENABLE_OCR:
      if (value == null) {
        unsetEnableOCR();
      } else {
        setEnableOCR((Boolean)value);
      }
      break;

    case ENABLE_OFFICE_OCR:
      if (value == null) {
        unsetEnableOfficeOCR();
      } else {
        setEnableOfficeOCR((Boolean)value);
      }
      break;

    case ENABLE_PDF_OCR:
      if (value == null) {
        unsetEnablePdfOCR();
      } else {
        setEnablePdfOCR((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STREAM:
      return getStream();

    case FILE_NAME:
      return getFileName();

    case ENABLE_OCR:
      return isEnableOCR();

    case ENABLE_OFFICE_OCR:
      return isEnableOfficeOCR();

    case ENABLE_PDF_OCR:
      return isEnablePdfOCR();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STREAM:
      return isSetStream();
    case FILE_NAME:
      return isSetFileName();
    case ENABLE_OCR:
      return isSetEnableOCR();
    case ENABLE_OFFICE_OCR:
      return isSetEnableOfficeOCR();
    case ENABLE_PDF_OCR:
      return isSetEnablePdfOCR();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ParseParams)
      return this.equals((ParseParams)that);
    return false;
  }

  public boolean equals(ParseParams that) {
    if (that == null)
      return false;

    boolean this_present_stream = true && this.isSetStream();
    boolean that_present_stream = true && that.isSetStream();
    if (this_present_stream || that_present_stream) {
      if (!(this_present_stream && that_present_stream))
        return false;
      if (!this.stream.equals(that.stream))
        return false;
    }

    boolean this_present_fileName = true && this.isSetFileName();
    boolean that_present_fileName = true && that.isSetFileName();
    if (this_present_fileName || that_present_fileName) {
      if (!(this_present_fileName && that_present_fileName))
        return false;
      if (!this.fileName.equals(that.fileName))
        return false;
    }

    boolean this_present_enableOCR = true;
    boolean that_present_enableOCR = true;
    if (this_present_enableOCR || that_present_enableOCR) {
      if (!(this_present_enableOCR && that_present_enableOCR))
        return false;
      if (this.enableOCR != that.enableOCR)
        return false;
    }

    boolean this_present_enableOfficeOCR = true;
    boolean that_present_enableOfficeOCR = true;
    if (this_present_enableOfficeOCR || that_present_enableOfficeOCR) {
      if (!(this_present_enableOfficeOCR && that_present_enableOfficeOCR))
        return false;
      if (this.enableOfficeOCR != that.enableOfficeOCR)
        return false;
    }

    boolean this_present_enablePdfOCR = true;
    boolean that_present_enablePdfOCR = true;
    if (this_present_enablePdfOCR || that_present_enablePdfOCR) {
      if (!(this_present_enablePdfOCR && that_present_enablePdfOCR))
        return false;
      if (this.enablePdfOCR != that.enablePdfOCR)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_stream = true && (isSetStream());
    list.add(present_stream);
    if (present_stream)
      list.add(stream);

    boolean present_fileName = true && (isSetFileName());
    list.add(present_fileName);
    if (present_fileName)
      list.add(fileName);

    boolean present_enableOCR = true;
    list.add(present_enableOCR);
    if (present_enableOCR)
      list.add(enableOCR);

    boolean present_enableOfficeOCR = true;
    list.add(present_enableOfficeOCR);
    if (present_enableOfficeOCR)
      list.add(enableOfficeOCR);

    boolean present_enablePdfOCR = true;
    list.add(present_enablePdfOCR);
    if (present_enablePdfOCR)
      list.add(enablePdfOCR);

    return list.hashCode();
  }

  @Override
  public int compareTo(ParseParams other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetStream()).compareTo(other.isSetStream());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStream()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stream, other.stream);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFileName()).compareTo(other.isSetFileName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFileName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fileName, other.fileName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEnableOCR()).compareTo(other.isSetEnableOCR());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEnableOCR()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.enableOCR, other.enableOCR);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEnableOfficeOCR()).compareTo(other.isSetEnableOfficeOCR());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEnableOfficeOCR()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.enableOfficeOCR, other.enableOfficeOCR);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEnablePdfOCR()).compareTo(other.isSetEnablePdfOCR());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEnablePdfOCR()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.enablePdfOCR, other.enablePdfOCR);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ParseParams(");
    boolean first = true;

    sb.append("stream:");
    if (this.stream == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.stream, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("fileName:");
    if (this.fileName == null) {
      sb.append("null");
    } else {
      sb.append(this.fileName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("enableOCR:");
    sb.append(this.enableOCR);
    first = false;
    if (!first) sb.append(", ");
    sb.append("enableOfficeOCR:");
    sb.append(this.enableOfficeOCR);
    first = false;
    if (!first) sb.append(", ");
    sb.append("enablePdfOCR:");
    sb.append(this.enablePdfOCR);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ParseParamsStandardSchemeFactory implements SchemeFactory {
    public ParseParamsStandardScheme getScheme() {
      return new ParseParamsStandardScheme();
    }
  }

  private static class ParseParamsStandardScheme extends StandardScheme<ParseParams> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ParseParams struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STREAM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.stream = iprot.readBinary();
              struct.setStreamIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FILE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.fileName = iprot.readString();
              struct.setFileNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ENABLE_OCR
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.enableOCR = iprot.readBool();
              struct.setEnableOCRIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ENABLE_OFFICE_OCR
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.enableOfficeOCR = iprot.readBool();
              struct.setEnableOfficeOCRIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ENABLE_PDF_OCR
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.enablePdfOCR = iprot.readBool();
              struct.setEnablePdfOCRIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ParseParams struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.stream != null) {
        oprot.writeFieldBegin(STREAM_FIELD_DESC);
        oprot.writeBinary(struct.stream);
        oprot.writeFieldEnd();
      }
      if (struct.fileName != null) {
        oprot.writeFieldBegin(FILE_NAME_FIELD_DESC);
        oprot.writeString(struct.fileName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ENABLE_OCR_FIELD_DESC);
      oprot.writeBool(struct.enableOCR);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ENABLE_OFFICE_OCR_FIELD_DESC);
      oprot.writeBool(struct.enableOfficeOCR);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ENABLE_PDF_OCR_FIELD_DESC);
      oprot.writeBool(struct.enablePdfOCR);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ParseParamsTupleSchemeFactory implements SchemeFactory {
    public ParseParamsTupleScheme getScheme() {
      return new ParseParamsTupleScheme();
    }
  }

  private static class ParseParamsTupleScheme extends TupleScheme<ParseParams> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ParseParams struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetStream()) {
        optionals.set(0);
      }
      if (struct.isSetFileName()) {
        optionals.set(1);
      }
      if (struct.isSetEnableOCR()) {
        optionals.set(2);
      }
      if (struct.isSetEnableOfficeOCR()) {
        optionals.set(3);
      }
      if (struct.isSetEnablePdfOCR()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetStream()) {
        oprot.writeBinary(struct.stream);
      }
      if (struct.isSetFileName()) {
        oprot.writeString(struct.fileName);
      }
      if (struct.isSetEnableOCR()) {
        oprot.writeBool(struct.enableOCR);
      }
      if (struct.isSetEnableOfficeOCR()) {
        oprot.writeBool(struct.enableOfficeOCR);
      }
      if (struct.isSetEnablePdfOCR()) {
        oprot.writeBool(struct.enablePdfOCR);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ParseParams struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.stream = iprot.readBinary();
        struct.setStreamIsSet(true);
      }
      if (incoming.get(1)) {
        struct.fileName = iprot.readString();
        struct.setFileNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.enableOCR = iprot.readBool();
        struct.setEnableOCRIsSet(true);
      }
      if (incoming.get(3)) {
        struct.enableOfficeOCR = iprot.readBool();
        struct.setEnableOfficeOCRIsSet(true);
      }
      if (incoming.get(4)) {
        struct.enablePdfOCR = iprot.readBool();
        struct.setEnablePdfOCRIsSet(true);
      }
    }
  }

}

